name: subregion-derivation
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.3.1
  - python=3.9.7
  - scikit-learn=1.0.2
  - pip:
    - black==21.10b0
    - cftime==1.5.1.1
    - eofs==1.4.0
    - dask==2022.2.1
    - distributed==2022.2.1
    - doit==0.34.1
    - geopandas==0.10.2
    - ipykernel==6.6.0
    - matplotlib==3.4.3
    - matplotlib-scalebar==0.8.1
    - netcdf4==1.5.8
    - numpy==1.21.4
    - openpyxl==3.0.9
    - pandas==1.3.4
    - proplot==0.9.5
    - pylint==2.11.1
    - pytest==6.2.5
    - pytest-cov==3.0.0
    - pytest-watch==4.2.0
    - rioxarray==0.10.2
    - seaborn==0.11.2
    - xarray==0.20.1
    - contextily==1.2.0
